services:
  db:
    image: postgres:16-alpine
    container_name: kontorutleie_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yourdb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  postgres_data: